export const interests = [
  "Drawing",
  "Photography",
  "Design",
  "Music",
  "Dancing",
  "Reading books",
  "Programming",
  "Languages",
  "History",
  "Psychology",
  "Fitness",
  "Yoga",
  "Running",
  "Swimming",
  "Extreme sports",
  "Video games",
  "Board games",
  "Movies",
  "Anime",
  "Role-playing games",
  "Traveling",
  "Hiking",
  "Fishing",
  "Gardening",
  "Cooking",
  "Coffee/Tea",
  "Sports",
  "Robotics",
  "DIY",
  "Cars/Motorcycles",
  "Volunteering",
  "Communities",
];